version: '3.4'

services:
  sd0xprojectdockertodolist:
    image: sd0xprojectdockertodolist
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
